name: localizable_annotation
description: An annotation for localizable, so Localization can be created automatically.
version: 0.0.3
repository: https://github.com/mbaguszulmi/localizable_annotation
homepage: https://github.com/mbaguszulmi/localizable_annotation

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:

dev_dependencies:
  test: ^1.20.0
  test_descriptor: ^2.0.0
  test_process: ^2.0.2
